Singolo 1.5
AlexGrin1/Simple-singolo pull request #6
Opened 2021-01-04 08:44 UTC by AlexGrin1

2021-01-05 19:59 UTC, zenby requested changes

2021-01-05 19:59 UTC, zenby commented on style.css
> +  overflow-x:hidden;
Нет, так делать не нужно. Это плохой хак, значит ты что-то сделал не так, раз тебе приходится использовать это свойство. Оно тут нужно будет максимум в секции со слайдером, но не больше.

2021-01-05 19:59 UTC, zenby commented on style.css
> +  flex-direction: row;
flex-direction: row - работает по дефолту, это можно не писать

2021-01-05 19:59 UTC, zenby commented on style.css
> +}
position: absolute - вызывает вопросы, для чего это нужно. 

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Examples
Вот что нужно оставить, чтобы расположить элементы далеко друг от друга в хедере. Посмотри плз на каждое из этих свойств для чего они нужны именно здесь. Останется чуток паддинги/маржины только поправить.
```
    max-width: 1020px;
    /* width: 1020px; */
    display: flex;
    /* flex-direction: row; */
    /* position: absolute; */
    /* top: 20px; */
    /* height: auto; */
    justify-content: space-between;
    width: 100%;
    align-items: center;
    padding: 0 20px;
```

Попробуй таким же образом исправить footer. У тебя опять там фиксация на 1020px.

2021-01-05 19:59 UTC, zenby commented on style.css
> +  height: auto;
Это свойство в большинстве случаях твоего использования не нужно.

2021-01-05 19:59 UTC, zenby commented on style.css
> +  width: 1020px;
Когда починишь футер замени тут на max-width: 1020px и все будет окей работать. В случае, если где-то опять что-то кривое получается в плане горизонтального скролла и причина в многих местах, то самый простой способ временно выключать по очереди секции с помощью `display: none` и чинить по одной.

2021-01-05 19:59 UTC, zenby commented on style.css
> +  overflow: hidden;
Такое в работе иногда может быть, но это сразу признак плохого кода. В учебных/тестовых проектах сразу маркер, что тут что-то не так. То есть по твоей структуре скролл хочет показаться, а ты его намеренно прячешь. Значит что-то не так.

2021-01-05 19:59 UTC, zenby commented on style.css
> +  overflow: hidden;
тоже разобраться с этим

2021-01-05 19:59 UTC, zenby commented on style.css
> +  overflow: hidden;
убрать
могу дать подсказку почему внизу появляется зазор небольшой
 изза того что в html ты использовал li для этих картинок и вверху на portfolio поставил line-height: 30px он наследует это значение.
 Варианты либо выпилить li совсем из html (они кстати не нужны) либо поправлять значения line-height в нужной иерархии

2021-01-05 19:59 UTC, zenby commented on index.html
> +            <img class="slide_image" src="./images/slide1.png" alt="images on phones">
тут есть небольшой нюанс. В этом случае скаченная картинка немного добавит головной боли при работе со слайдером (потому что тут есть бекграунд, и она плохо скейлится).
Мой совет такой, скачай эту картинку с двумя телефонами из сайдбара проекта в figma. Там есть пункт сохранить в svg. Сохрани такую же картинку под именем `slide1.svg` и попробуй её заюзать.

2021-01-05 19:59 UTC, zenby commented on style.css
> +  bottom: 80.39%;
достаточно 2 значений: 1 горизонтального, 1 вертикального и все будет работать.
Но вообще я попрошу тебя расположить стрелку строго по центру по вертикали. Для подобных случаев есть такой пример, как это делать. https://codepen.io/jscodelover/pen/EGXZEM

2021-01-05 19:59 UTC, zenby commented on style.css
> +.arrow-right:hover{
```
.arrow-left:hover,
.arrow-right:hover {
```
чтобы избежать дублирования двух одинаковых блоков

2021-01-05 19:59 UTC, zenby commented on style.css
> +  height: auto;
как правило многие из свойств *: auto у тебя не нужны,

2021-01-05 19:59 UTC, zenby commented on style.css
> +a:active {
можно объединить эти 2 блока в один

2021-01-05 19:59 UTC, zenby commented on style.css
> +}
Еще разные браузеры по дефолту добавляют свои паддинги маржины по дефолту. Иногда можно на это напороться. Часто верстка начинается с того, что добавляют такой код, чтобы все обнулить. К слову, есть более сложные правила для этого и для больших параметров. 
```
* {
margin: 0;
padding: 0;
}
```

2021-01-05 20:01 UTC, zenby commented on index.html
> +            </nav>
Я в прошлом ПРе просил убрать ссылки на точки, а не сами точки. Добавь их плз, раз они нужны по макету.

2021-01-05 20:32 UTC, AlexGrin1 commented on style.css
> +  overflow: hidden;
Дело в том, что в задании вот что требуется: 
 - "Если в текстовой ячейке больше текста, чем она вмещает, и текст начинает выходить за границы элемента, то выступающая часть должна быть скрыта." 
 поэтому применил это свойство. Или это делается по другому?

2021-01-05 20:32 UTC, AlexGrin1 commented on style.css
> +  overflow: hidden;
аналогично

2021-01-05 20:34 UTC, AlexGrin1 commented on style.css
> +  overflow: hidden;
Тут такая же история :
 - "Если в сетку добавить больше элементов с изображениями (например, 15) - то следующие за 12-м не должны показываться (т.е. 13, 14, 15 не видны)."

2021-01-06 12:57 UTC, zenby commented on style.css
> +  overflow: hidden;
Если бы оно работало, то тогда при добавлении у тебя еще пары картинок, оно бы не показывалось. А сейчас у тебя они показываются, то есть свойство не работает и лишнее.
Я понимаю как сделать то, что требуется при помощи `nth-child` можешь почитать про этот вид псевдо класса.

2021-01-06 13:04 UTC, zenby commented on style.css
> +  overflow: hidden;
да, согласно требованиям это можно оставить
Хотя, если честно, впервые вижу, чтобы где-то приходилось так обрубать текст.

2021-01-06 13:05 UTC, zenby commented on style.css
> +  overflow: hidden;
А вот тут это не нужно. Текста в блоке ведь нету, только картинки.

2021-01-06 13:08 UTC, zenby commented
Кстати можешь еще добавить favicon, чтобы твоё приложение когда во вкладке браузера открыто показывало какую-нибудь иконку.

2021-01-14 21:02 UTC, zenby commented
## Критерии оценки - максимальный балл за задание - 200 баллов

### Вёрстка десктопной версии сайта +40 (из 50)

#### 1. **Header** (`<header>` содержит только логотип и панель навигации) +10

- [x] Интерактивная панель навигации.
- [x] Логотип содержит 2 разных текстовых элемента, белый и красный.
- [x] На странице обязательно должен присутствовать один элемент `<h1>`. Расположите его на свое усмотрение.
- [x] Внизу есть небольшая линия другого цвета, будьте внимательны.

#### 2. Блок **Slider** +10

- [x] Стрелки должны быть интерактивными.

#### 3. Блок **Our Services** +10

- [x] Трёхколоночный макет снизу. Лучше использовать [flexbox](https://habr.com/ru/post/467049/) или [grid](https://tuhub.ru/posts/css-grid-complete-guide). Float использовать можно. `<table>` - нельзя!
- [x] Изображения можно экспортировать как иконки вместе с кругами. Другой вариант - экспортировать только сами иконки, а круги добавить свойством `border-radius`.
- [x] Если в текстовой ячейке больше текста, чем она вмещает, и текст начинает выходить за границы элемента, то выступающая часть должна быть скрыта.

~#### 4. Блок **Portfolio** +10~

- [x] Интерактивные кнопки навигации.
- [ ] Четырех колоночный макет с изображениями. 
_Отступы не соответствуют макету._
![image](https://user-images.githubusercontent.com/32563455/104646678-d5c3fc00-56c1-11eb-9f9a-6709d563d914.png)
_Можешь попробовать исправить стили_
```
// container
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-column-gap: 20px;
    grid-row-gap: 20px;

// images
  width: 100%;
```
_У тебя будут изображения масштабироваться но тебе главное сделать так, чтобы на нужные ширины экрана показывало нужные отступы. Все что между не описано - делай как тебе удобно. Также нужно, чтобы по вертикали и горизонтали они были одинаковые._

- [x] Если в сетку добавить больше элементов с изображениями (например, 15) - то следующие за 12-м не должны показываться (т.е. 13, 14, 15 не видны).

#### 5. **Footer** (`<footer>` - это серая панель снизу) +10

- [x] Символ "копирайт" (©) должен быть текстовым, т.е. чтобы при выделении текста мышкой, он также выделялся.
- [x] Интерактивные иконки

### Адаптивная вёрстка с использованием медиазапросов +45 (из 100)

#### 1020px <= width

#### Background +10

- [x] Цвет блоков продолжается на всю доступную область окна браузера, обёртка центрируется.

#### 768px <= width < 1020px

~#### Header +10~

- [ ] Логотип слева и крайний элемент меню навигации справа сохраняют свои отступы до краёв блока header.
_Тут субъективный немного пункт. Но факт в том, что у тебя нету по 40px слева справа._

#### Slider +5

- [x] Изображения телефонов должны быть уменьшены до значений ширины и высоты, как на макете Tablet-768.

#### Our services +10

- [ ] Сетка из трех-колоночной становится двух-колоночной. **3 х 2** становится **2 х 3**.

- [ ] Меняются расстояния как от элементов сетки до краев блока, так и расстояние между соседствующими элементами, главное, чтобы значения позиционирования совпали с отступами в макете Tablet-768 при такой же ширине окна браузера в 768px.

~#### Portfolio +10~

- [x] Сетка из четырех-колоночной становится трех-колоночной. **4 х 3** становится **3 х 4**.

- [ ] Отступы между элементами сохраняются. Отступы до краев блока сохраняются. Вплоть до 768px.
_Отступы не соответствуют макету_

~#### Footer +5~

- [ ] Копирайт слева и крайняя иконка соц. сетей справа сохраняют свои отступы до краев блока footer.
 _Отступы не соответствуют макету слева справа не 40px_

### 375px <= width < 768px

#### Header +10

- [x] Логотип остается в центре. Верхнее меню навигации скрывается в бургер-меню слева.

#### Slider +5

- [x] На картинке _Slide-1_ телефоны должны быть уменьшены до значений ширины и высоты на экране 375px.

~#### Our services +10~

- [x] Сетка из двух-колоночной становится в одну колонку. **2 х 3** становится **1 х 6**.

- [ ] Меняются расстояния как от элементов сетки до краев блока, так и расстояние между соседствующими элементами, главное, чтобы значения позиционирования совпали с отступами в макете Mobile-375 при такой же ширине окна браузера в 375px.
_Отступы не соответствуют макету_

~#### Portfolio +10~

- [x] Сетка из трех-колоночной становится двух-колоночной, высотой в 4 строки. Остальные элементы должны быть скрыты. **3 х 4** становится **2 х 4**.
- [ ] Отступы между элементами и до краев блока должны измениться до значений ширины и высоты на экране 375px.
_Отступы не соответствуют макету_

#### Footer +5

- [x] Копирайт пропадает со страницы. Иконки соц. сетей центрируются в блоке footer.

~### width < 375px +10~

- [ ] Минимальная ширина макета = 320px. После порогового значения расположение верстки значения не имеет. Структура верстки остается такой же, как при ширине 375px. При уменьшении страницы с 375px до 320px, структура верстки (отступы, размеры блоков и др.) остаются по расположению как на макете Mobile-375.
_Ломается вид на слайдер при уже 375px_
![image](https://user-images.githubusercontent.com/32563455/104648733-9f3bb080-56c4-11eb-82e9-aebabb50defb.png)


- [ ] Cтраница не должна разваливаться, что значит, что отступы, размеры блоков, и прочее, не должны уходить за правый край экрана и не должен появляться горизонтальный скролл.
_См. пункт выше_

## Добавление интерактивности +0 (из 50)

~### Header +20~

- [ ] Сделать меню с переключением. Активным остается выбранный элемент меню, предыдущий становится неактивным. Страница должна при этом переходить по якорям в заданную позицию с плавной анимацией. При переходе и скролле, активным должен становиться элемент меню того блока, на котором находится текущая позиция.

- [ ] Если последний элемент, который имеет ссылку в меню навигации, при скролле верхней границей блока физически не может достигнуть верхней границы окна браузера, то активный элемент может не подсвечиваться, но скролл должен происходить. Если вы сделаете так, что элемент будет подсвечен, ошибкой это считаться не будет.

- [ ] При ширине экрана меньше 768px верхнее меню навигации скрывается в бургер-меню слева. По нажатию на бургер-меню, должна отображаться панель слева, которая перекрывает экран приложения. Важно, что, какой бы ни была высота окна браузера, блок меню должен занимать всю высоту. Ширину брать из макета. Также, иконка сэндвича должна поворачиваться, как на макете. При нажатии на ссылку, мы должны перейти по якорю к нужной позиции, а меню должно скрыться, и иконка вернуться в прежнее состояние.

~### Slider. Переключение слайдов +20~

- [ ] Есть 2 слайда. Нужно добавить вторую картинку _Slide-2_. Сделать взаимодействие с кнопками, при нажатии на которые, карусель должна менять изображение на новое. Карусель должна быть бесконечной, т.е. можно все время нажимать "вправо", и картинки будут постоянно меняться. Этот элемент не обязательно делать наложением слоев, достаточно сделать его просто картинкой целиком. Стрелки при этом могут оставаться того же цвета. Изменение цвета стрелок на другой при перелистывании на слайд с синим цветом фона, не является ошибкой при проверке.

- [ ] Слайды должны перелистываться, т.е. должна присутствовать анимация выезда картинки справа или слева. [Пример](https://itchief.ru/examples/lab.php?topic=javascript&file=chiefslider-with-refresh)

~### Portfolio. Переключение табов +10~

- [ ] При переключении табов в верхней части блока, новый таб должен становиться активным. Картинки снизу, должны менять свои позиции, сдвигаясь на одинаковую величину. Либо они должны перемещаться в случайном порядке. Главное, чтобы те же картинки не оставались на своем месте. Активный таб можно сделать не кликабельным и не интерактивным - это не является ошибкой.

- [ ] Изменение последовательности должно происходить изменением порядка или перемешиванием (shuffle) DOM элементов в JavaScript.

2021-01-14 21:13 UTC, zenby commented on style.css
> +  top: 44%;
Я скидывал ссылку как расположить элемент по центру (вертикали) с помощью position absolute. Сейчас тут подобрано тобой число, чтобы выглядело нормально, однако его трудоемко подбирать всякий раз когда тебе нужно это сделать.
Хорошо, чтобы ты нашел и знал как это сделать правильно.

2021-01-14 21:13 UTC, zenby commented on style.css
> +  grid-template-rows: 120px 120px;
изза этого свойства у тебя на 600px появляется разная высота строк

2021-01-14 21:13 UTC, zenby commented on style.css
> +  list-style-type: none;
лишнее

2021-01-16 10:34 UTC, zenby commented on script.js
> +});
По поводу карточек в портфолио, у тебя в консоли ошибка падает, если ты на web кликаешь и они не перемешиваются (засчитывают баллы только если все картинки перемешиваются)
Также советую тебе немного переработать эту логику, потому что очень много кода лишнего (4 блока в каждом по 4 строки. А если этих кнопок 20 будет, сделаешь 20х20?).
Для того, чтобы исправить почитай про [делегирование](https://learn.javascript.ru/behavior) и https://learn.javascript.ru/event-delegation#the-behavior-pattern

Если вкратце
- повесить один обработчик на контейнер с кнопками
- в момент клика по контейнеру проверить кнопка ли эта

  - если кнопка, то убрать со всех кнопок filter_button_active
  - если не кнопка не делать ничего
Дальше
- взять класс элемента как у тебя (но вообще лучше `data-*` атрибут)
- сделать элемент активным (навесить `filter_button_active`)
- выполнить какую-то логику связанную с данными в этом атрибуте (либо показать только данные картинки, либо просто перемешать все подряд)

2021-01-16 10:40 UTC, zenby commented on script.js
> +const link_contact = header_link.querySelector('.cont');
исправить все переменные в camelCase нотацию

2021-01-20 20:36 UTC, zenby commented on script.js
> +})
- можно из 4 блоков сделать один
- сравнение всегда делай через `===` а не `==`

2021-01-20 20:36 UTC, zenby commented on style.css
> +  transform: translateY(-50%, -50%) scale(1.5);
это свойство сейчас не срабатывает в браузере изза ошибки в записи

2021-01-21 09:38 UTC, zenby commented on style.css
> +  transform: scale(1.7);
![Peek 2021-01-21 12-36](https://user-images.githubusercontent.com/32563455/105332180-611f1f00-5be5-11eb-8a88-22dd41da8419.gif)
из-за того, что когда у тебя стрелка в hover состоянии у нее нету translateY она прыгает вниз

2021-01-25 08:29 UTC, zenby requested changes

2021-01-25 08:29 UTC, zenby commented on script.js
> +})
- исправить форматирование
- убрать везде console.log() (для финального варианта)
- давай осмысленные названия переменных и везде где можно используй const 
- переставь из header `data-name` на секцию со слайдером
- заиспользуй функцию `debounce` [отсюда](https://frontend-stuff.com/blog/debounce-in-javascript/) с временем ожидания 100ms на твой скролл. И почитай эту статью для чего это нужно.

2021-01-28 08:46 UTC, zenby approved these changes
## Критерии оценки - максимальный балл за задание - 200 баллов

### Вёрстка десктопной версии сайта +50

#### 1. **Header** (`<header>` содержит только логотип и панель навигации) +10

- [x] Интерактивная панель навигации.
- [x] Логотип содержит 2 разных текстовых элемента, белый и красный.
- [x] На странице обязательно должен присутствовать один элемент `<h1>`. Расположите его на свое усмотрение.
- [x] Внизу есть небольшая линия другого цвета, будьте внимательны.

#### 2. Блок **Slider** +10

- [x] Стрелки должны быть интерактивными.

#### 3. Блок **Our Services** +10

- [x] Трёхколоночный макет снизу. Лучше использовать [flexbox](https://habr.com/ru/post/467049/) или [grid](https://tuhub.ru/posts/css-grid-complete-guide). Float использовать можно. `<table>` - нельзя!
- [x] Изображения можно экспортировать как иконки вместе с кругами. Другой вариант - экспортировать только сами иконки, а круги добавить свойством `border-radius`.
- [x] Если в текстовой ячейке больше текста, чем она вмещает, и текст начинает выходить за границы элемента, то выступающая часть должна быть скрыта.

#### 4. Блок **Portfolio** +10

- [x] Интерактивные кнопки навигации.
- [x] Четырех колоночный макет с изображениями.
- [x] Если в сетку добавить больше элементов с изображениями (например, 15) - то следующие за 12-м не должны показываться (т.е. 13, 14, 15 не видны).

#### 5. **Footer** (`<footer>` - это серая панель снизу) +10

- [x] Символ "копирайт" (©) должен быть текстовым, т.е. чтобы при выделении текста мышкой, он также выделялся.
- [x] Интерактивные иконки

### Адаптивная вёрстка с использованием медиазапросов +100

#### 1020px <= width

#### Background +10

- [x] Цвет блоков продолжается на всю доступную область окна браузера, обёртка центрируется.

#### 768px <= width < 1020px

#### Header +10

- [x] Логотип слева и крайний элемент меню навигации справа сохраняют свои отступы до краёв блока header.
![image](https://user-images.githubusercontent.com/32563455/106111687-676d4800-615d-11eb-9654-1da7bc32c6b9.png)


#### Slider +5

- [x] Изображения телефонов должны быть уменьшены до значений ширины и высоты, как на макете Tablet-768.

#### Our services +10

- [x] Сетка из трех-колоночной становится двух-колоночной. **3 х 2** становится **2 х 3**.

- [x] Меняются расстояния как от элементов сетки до краев блока, так и расстояние между соседствующими элементами, главное, чтобы значения позиционирования совпали с отступами в макете Tablet-768 при такой же ширине окна браузера в 768px.

#### Portfolio +10

- [x] Сетка из четырех-колоночной становится трех-колоночной. **4 х 3** становится **3 х 4**.

- [x] Отступы между элементами сохраняются. Отступы до краев блока сохраняются. Вплоть до 768px.

#### Footer +5

- [ ] Копирайт слева и крайняя иконка соц. сетей справа сохраняют свои отступы до краев блока footer.
Отступ слева неверный
![image](https://user-images.githubusercontent.com/32563455/106111875-a3081200-615d-11eb-8fb6-5cd3a4a26b60.png)


### 375px <= width < 768px

#### Header +10

- [x] Логотип остается в центре. Верхнее меню навигации скрывается в бургер-меню слева.

#### Slider +5

- [x] На картинке _Slide-1_ телефоны должны быть уменьшены до значений ширины и высоты на экране 375px.

#### Our services +10

- [x] Сетка из двух-колоночной становится в одну колонку. **2 х 3** становится **1 х 6**.

- [ ] Меняются расстояния как от элементов сетки до краев блока, так и расстояние между соседствующими элементами, главное, чтобы значения позиционирования совпали с отступами в макете Mobile-375 при такой же ширине окна браузера в 375px.
Есть лишний отступ справа от текста (текст сверху и описание сервиса должны быть четко один под одним)
![image](https://user-images.githubusercontent.com/32563455/106112090-e4002680-615d-11eb-962c-18755363f480.png)


#### Portfolio +10

- [x] Сетка из трех-колоночной становится двух-колоночной, высотой в 4 строки. Остальные элементы должны быть скрыты. **3 х 4** становится **2 х 4**.
- [x] Отступы между элементами и до краев блока должны измениться до значений ширины и высоты на экране 375px.

#### Footer +5

- [ ] Копирайт пропадает со страницы. Иконки соц. сетей центрируются в блоке footer.
Не центрируются

### width < 375px +10

- [x] Минимальная ширина макета = 320px. После порогового значения расположение верстки значения не имеет. Структура верстки остается такой же, как при ширине 375px. При уменьшении страницы с 375px до 320px, структура верстки (отступы, размеры блоков и др.) остаются по расположению как на макете Mobile-375.

- [x] Cтраница не должна разваливаться, что значит, что отступы, размеры блоков, и прочее, не должны уходить за правый край экрана и не должен появляться горизонтальный скролл.

## Добавление интерактивности +50

### Header +20

- [x] Сделать меню с переключением. Активным остается выбранный элемент меню, предыдущий становится неактивным. Страница должна при этом переходить по якорям в заданную позицию с плавной анимацией. При переходе и скролле, активным должен становиться элемент меню того блока, на котором находится текущая позиция.

- [x] Если последний элемент, который имеет ссылку в меню навигации, при скролле верхней границей блока физически не может достигнуть верхней границы окна браузера, то активный элемент может не подсвечиваться, но скролл должен происходить. Если вы сделаете так, что элемент будет подсвечен, ошибкой это считаться не будет.

- [x] При ширине экрана меньше 768px верхнее меню навигации скрывается в бургер-меню слева. По нажатию на бургер-меню, должна отображаться панель слева, которая перекрывает экран приложения. Важно, что, какой бы ни была высота окна браузера, блок меню должен занимать всю высоту. Ширину брать из макета. Также, иконка сэндвича должна поворачиваться, как на макете. При нажатии на ссылку, мы должны перейти по якорю к нужной позиции, а меню должно скрыться, и иконка вернуться в прежнее состояние.

### Slider. Переключение слайдов +20

- [x] Есть 2 слайда. Нужно добавить вторую картинку _Slide-2_. Сделать взаимодействие с кнопками, при нажатии на которые, карусель должна менять изображение на новое. Карусель должна быть бесконечной, т.е. можно все время нажимать "вправо", и картинки будут постоянно меняться. Этот элемент не обязательно делать наложением слоев, достаточно сделать его просто картинкой целиком. Стрелки при этом могут оставаться того же цвета. Изменение цвета стрелок на другой при перелистывании на слайд с синим цветом фона, не является ошибкой при проверке.

- [ ] Слайды должны перелистываться, т.е. должна присутствовать анимация выезда картинки справа или слева. [Пример](https://itchief.ru/examples/lab.php?topic=javascript&file=chiefslider-with-refresh)
Анимация отсутствует.

### Portfolio. Переключение табов +10

- [x] При переключении табов в верхней части блока, новый таб должен становиться активным. Картинки снизу, должны менять свои позиции, сдвигаясь на одинаковую величину. Либо они должны перемещаться в случайном порядке. Главное, чтобы те же картинки не оставались на своем месте. Активный таб можно сделать не кликабельным и не интерактивным - это не является ошибкой.

- [x] Изменение последовательности должно происходить изменением порядка или перемешиванием (shuffle) DOM элементов в JavaScript.

В целом все выглядит неплохо, есть небольшие неточности со скроллом и переходом по ссылкам.
За вычетом пунктов, где есть ошибки выходит **150** . Если поправишь верстку будет **180**

2021-02-03 19:58 UTC, merged